name: sc_pdb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas==2.3.2
  - numpy==2.3.1
  - scikit-learn==1.7.1
  - seaborn==0.13.2
  - matplotlib==3.10.5
  - pymol-open-source==3.1.0
  - trimesh==4.7.4
  - biopython==1.85
  - networkx==3.5
